Add support for Unity with Gradle 8+
Unity-Technologies/com.unity.mobile.notifications pull request #300
Opened 2023-11-30 10:58 UTC by manugildev

Starting with AGP 8+, module's `build.gradle`files are **required** to have the `namespace` property. This is supposed to replace the package attribute on the `AndroidManifest.xml` file.

Error before:
``` 
A problem occurred configuring project ':unityLibrary:mobilenotifications.androidlib'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.
```

**Testing**
- ✅  Tested using the AutomatedTests project. All test passing after the change.

2023-11-30 12:06 UTC, aurimasc requested changes

2023-11-30 12:06 UTC, aurimasc commented on com.unity.mobile.notifications/Runtime/Android/Plugins/mobilenotifications.androidlib/build.gradle
> +    namespace "com.unity.androidnotifications"
I see that 21.3 is failing due to this. 
Looks like this is a way to fix it: https://stackoverflow.com/questions/76108428/how-do-i-fix-namespace-not-specified-error-in-android-studio

2023-11-30 12:49 UTC, aurimasc commented on com.unity.mobile.notifications/Runtime/Android/Plugins/mobilenotifications.androidlib/build.gradle
> +    if (project.android.hasProperty("namespace")) {
Could you add a comment that this is for Unity 21.3, so we can clean this up when dropped.
Also mention package in the manifest, I think it's not required after namespace is here.

2023-11-30 13:27 UTC, aurimasc approved these changes

2023-12-04 10:35 UTC, aurimasc approved these changes

2023-12-04 15:53 UTC, JacobSimpson-unity approved these changes
Small change to add compatibility for Gradle 8 requirements. Thoroughly tested by Manuel, no additional testing required.

2023-12-05 07:47 UTC, merged