Use Android project modifier for post-processing
Unity-Technologies/com.unity.mobile.notifications pull request #326
Opened 2024-09-25 11:00 UTC by aurimasc

2024-09-26 06:51 UTC, aurimasc commented on com.unity.mobile.notifications/Editor/AndroidNotificationPostProcessor.cs
> +                    // TODO: Missing AddUsesPermissionSdk23 function
Hm, does not seem to be the case: https://docs.unity3d.com/6000.0/Documentation/ScriptReference/Unity.Android.Gradle.Manifest.Manifest.html

Strangely, we do have UsesPermissionSdk23List. Or does it mean one should call AddElement() on a list returned by that one?

2024-09-26 07:19 UTC, aurimasc commented on com.unity.mobile.notifications/Editor/AndroidNotificationPostProcessor.cs
> +    public class AndroidNotificationPostProcessor : AndroidProjectFilesModifier
Removed.

2024-09-26 08:41 UTC, todi1856 commented on com.unity.mobile.notifications/Editor/AndroidNotificationPostProcessor.cs
> +                    // TODO: Missing AddUsesPermissionSdk23 function
it seems we forgot to adds docs, but should do you something like this
```
batterOptimizations.AddUsesPermissionSdk23("android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS");
```
and that's it.

(Please validate that it does add it correctly)

2024-09-26 12:05 UTC, aurimasc commented on com.unity.mobile.notifications/Editor/AndroidNotificationPostProcessor.cs
> +            var receiverNotificationRestartOnBoot = new Receiver();
Fixed.

2024-09-26 12:05 UTC, aurimasc commented on com.unity.mobile.notifications/Editor/AndroidNotificationPostProcessor.cs
> +                    // TODO: Missing AddUsesPermissionSdk23 function
Yes, it works.
I've also changed defines to Unity 6.

2024-09-26 13:03 UTC, todi1856 approved these changes

2024-10-04 10:36 UTC, IGuscin requested changes
Found small issue on older Unity version (2022.3, issue exist in main as well, so not introduced by this PR) that entries are not removed from manifest when settings are changed. i.e. export project and check manifest when Schedule at exact time = nothing. Then do the same with Everything. And again with Nothing. Manifest will remain the same as with Everything.
Same issue is not reproducible on Unity 6, since the way manifest generated differs.
Otherwise looks good, manifest content is basically the same (package="com.unity.androidnotifications"> is now missing, but that's expected and order of elements is a bit different, but that doesn't impact functionality)

2024-10-04 11:32 UTC, IGuscin approved these changes

2024-10-04 11:36 UTC, merged