Case 1288346: iOS Notification Settings don't get printed in the test project
Unity-Technologies/com.unity.mobile.notifications pull request #81
Opened 2021-02-25 16:48 UTC by aurimasc

The reason is stripping. Because properties are not used, they get stripped and then reflection does not find them.
Unfortunately link.xml is not supported in packages.
Introduced field printing support instead.

2021-02-25 22:48 UTC, todi1856 requested changes

2021-02-25 22:48 UTC, todi1856 commented on TestProjects/com.unity.mobile-notifications-sample/Scripts/Helpers/Logger.cs
> +                Blue($"{field.Name}: {value}");
don't you need to pass tabs to Blue function  ? :)

2021-03-02 09:14 UTC, aurimasc commented
> Current fix is working, however, I'm assuming you might want to take into consideration Tomas' adjustment?

Haven't I fixed that with the last commit?

2021-03-02 09:28 UTC, vaidasma commented
Oh okay, I thought maybe you haven't seen it yet

2021-03-02 09:28 UTC, vaidasma approved these changes

2021-03-03 10:39 UTC, todi1856 approved these changes

2021-03-03 10:40 UTC, merged